### ISSUE TITLE
There is a problem with the screen width

### ISSUE THREAD

**Issue by theoyuncu8** [zhpanvip/viewpagerindicator#27]
When I look at the layout view, it looks something like this. .width looks like this even though I made 100 dp? I wonder why?

also there is notifyDataChanged in the codes, does this not cause performance problems?

![Ekran Alıntısı](https://user-images.githubusercontent.com/97362820/235308043-a31e8f42-dfa2-4ecd-a9eb-53c6aeae694d.PNG)

**Comment by zhpanvip** [comment]
The width and height of IndicatorView are dynamically set, which is related to the pagesize you set and the width and height of the slider.Since these parameters are not available in the preview, it seems that there will be problems. `notifyDataChanged` This method is only to update the View, there will be no performance loss
